# Generated by Django 4.1.7 on 2023-03-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clap",
            name="total_familias",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clap",
            name="total_litros",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="municipio",
            name="total_familias",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="municipio",
            name="total_litros",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="parroquia",
            name="total_familias",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="parroquia",
            name="total_litros",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sector",
            name="total_familias",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sector",
            name="total_litros",
            field=models.IntegerField(default=0),
        ),
    ]
