# Generated by Django 4.1.7 on 2023-03-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning_app", "0002_clap_total_familias_clap_total_litros_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clap",
            name="nombre_clap",
            field=models.CharField(max_length=30, verbose_name="Nombre Clap"),
        ),
        migrations.AlterField(
            model_name="municipio",
            name="nombre_mun",
            field=models.CharField(max_length=30, verbose_name="Nombre Municipio"),
        ),
        migrations.AlterField(
            model_name="parroquia",
            name="nombre_par",
            field=models.CharField(max_length=30, verbose_name="Nombre PArroquia"),
        ),
        migrations.AlterField(
            model_name="sector",
            name="nombre_sec",
            field=models.CharField(max_length=30, verbose_name="Nombre Sector"),
        ),
    ]
